### ISSUE TITLE
Sharing iP code quality feedback [for @s-peiran]

### ISSUE THREAD

**Issue by soc-se-bot-red** [s-peiran/ip#1]
@s-peiran We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

Example from [`src/main/java/tasks/Task.java` lines `5-5`](https://github.com/s-peiran/ip/blob/ef139dfd4677367cca2d4eeb44a470085ca26dfc/src/main/java/tasks/Task.java#L5..L5):

```java

    private boolean marked;

``` 

**Suggestion:** Follow the given naming convention for boolean variables/methods (e.g., use a boolean-sounding prefix).You may ignore the above if you think the name already follows the convention (the script can report false positives in some cases)

### Aspect: Brace Style

No easy-to-detect issues :+1: 

### Aspect: Package Name Style

No easy-to-detect issues :+1: 

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

Example from [`src/main/java/functional/Storage.java` lines `49-49`](https://github.com/s-peiran/ip/blob/ef139dfd4677367cca2d4eeb44a470085ca26dfc/src/main/java/functional/Storage.java#L49..L49):

```java

        // System.out.println("Opening Saved File");

```

Example from [`src/main/java/functional/Storage.java` lines `63-63`](https://github.com/s-peiran/ip/blob/ef139dfd4677367cca2d4eeb44a470085ca26dfc/src/main/java/functional/Storage.java#L63..L63):

```java

        // System.out.println("Saving file");

```

Example from [`src/main/java/functional/Storage.java` lines `73-73`](https://github.com/s-peiran/ip/blob/ef139dfd4677367cca2d4eeb44a470085ca26dfc/src/main/java/functional/Storage.java#L73..L73):

```java

        // System.out.println("File successfully Saved");

``` 

**Suggestion:** Remove dead code from the codebase.

### Aspect: Method Length

No easy-to-detect issues :+1: 

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/commands/Command.java` lines `32-36`](https://github.com/s-peiran/ip/blob/ef139dfd4677367cca2d4eeb44a470085ca26dfc/src/main/java/commands/Command.java#L32..L36):

```java

    /**
     * indicate to duke.Husky class whether it is time to end the program
     *
     * @return boolean of whether to end the program
     */

```

Example from [`src/main/java/functional/DukeException.java` lines `16-20`](https://github.com/s-peiran/ip/blob/ef139dfd4677367cca2d4eeb44a470085ca26dfc/src/main/java/functional/DukeException.java#L16..L20):

```java

    /**
     * toString method of DukeException thats prints the error msg
     *
     * @return the error message to be printed
     */

```

Example from [`src/main/java/functional/Storage.java` lines `28-33`](https://github.com/s-peiran/ip/blob/ef139dfd4677367cca2d4eeb44a470085ca26dfc/src/main/java/functional/Storage.java#L28..L33):

```java

    /**
     * Load the task stored in the local drive
     *
     * @return TaskList retrieved from the drive
     * @throws functional.DukeException
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by s-peiran** [comment]
all issues mentioned are rectified
